### ISSUE TITLE
Error Dispatching Chat Event

### ISSUE THREAD

**Issue by derverdox** [AuraDevelopmentTeam/BungeeChat2#84] opened 2019-03-31 20:07 UTC
#### Issue Description: 

The Chatevent does not work sometimes. The Vanilla Chat Format of the game server is shown instead

#### What happens:

The Sender sends a message and the BungeeChat Plugin should get the message and apply the format configured in the config.
But instead it keeps sending this error and shows the normal chat message format of the gameserver. The Chat message is not visible for the other gameservers in the bungeecord network

#### Steps to reproduce:

Unfortunately i dont know when or why this error is coming up

____
#### Affected Versions: 

BungeeCord Version LATEST
BungeeChat Latest available Version

#### Your most recent log or stack trace file where the issue was present: 

```
[21:56:31 WARN]: Error dispatching event ChatEvent(super=TargetedEvent(sender=Huaba_TV, receiver=net.md_5.bungee.ServerConnection@2f0f65dd), cancelled=false, message=vk billig brot) to listener dev.aura.bungeechat.listener.ChannelTypeCorrectorListener@428fa32
java.util.NoSuchElementException: No value present
at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_191]
at dev.aura.bungeechat.listener.ChannelTypeCorrectorListener.onPlayerChat(ChannelTypeCorrectorListener.java:30) ~[?:?]
at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at net.md_5.bungee.event.EventBus.post(EventBus.java:46) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:432) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:146) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by BrainStone** [comment] 2019-04-01 15:42
> BungeeCord Version LATEST
> BungeeChat Latest available Version

And these versions are?

And lastly I think this has been fixed in dev.

**Comment by BrainStone** [comment] 2019-04-01 15:42
Also duplicate of #54

**Closed by BrainStone** 2019-04-01 15:42 UTC
Labels: Bug
