### ISSUE TITLE
Private Messages - Could not find that player

### ISSUE THREAD

**Issue by Hodel1** [AuraDevelopmentTeam/BungeeChat2#5] opened 2017-06-19 08:23 UTC
Hi, I again, again :D 

We tested now the Private Message System. There is a Problem!
I get the Message randomly for "Could not find that player".
A relogin should fix it, but not always.

Here is a Screenshot: https://puu.sh/wofe5/b17fdc9f5e.png
The error is raised as i wrote a msg to mieepmieep

Tested again with Hexacord and Bungee Chat 2.0.3.1

**Comment by BrainStone** [comment] 2017-06-19 16:28
Oh boy. That's interesting. Do you get the message when using `/msg <player>` or `/r`?

**Comment by shawn-ian** [comment] 2017-06-19 16:48
@Hodel1 which version of HexaCord are you using?

**Comment by Hodel1** [comment] 2017-06-19 18:13
i'm sure, that was for both variants.
Here is a quote of /bungee

> 20:12:39	bds	[CHAT] This server is running HexaCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:fcceddd:unknown by md_5
> 20:12:39	bds	[CHAT] Protocol support for 1.7.x by Zartec, ghac and I9hdkill

**Comment by shawn-ian** [comment] 2017-06-20 06:55
Tried to reproduce this bug, but did not get any. (HexaCord 1.11; 10 server network). Do you have any errors in the console?

**Comment by Hodel1** [comment] 2017-06-20 10:29
i will look, when i get this error next time :)

**Comment by Hodel1** [comment] 2017-06-21 13:27
There is no error/exception in the bungeecord log

**Comment by Hodel1** [comment] 2017-06-22 18:05
Could you Reproduce this bug?

**Comment by BrainStone** [comment] 2017-06-22 18:50
Not yet.

**Comment by Hodel1** [comment] 2017-06-23 14:40
It seems, for spontanous error.
I have noticed that, the error is often to another Player in other Groups.
A player can whisper others but no Moderator. The Moderator has often this prob to whisper to Player or Administrators.

Could it be, that it is a fault with Bungeeperms?

**Comment by BrainStone** [comment] 2017-06-24 00:08
I don't think so tbh.
Do you have discord? If so could you visit our discord (https://discord.me/bungeechat) then I can give a debug build.

**Comment by BrainStone** [comment] 2017-06-24 19:49
I finnally found the root cause. When using FileStorage the fields messenger and vanished are switched around. Which caused this bug. But it's fixed now.
Fix will be included in 2.0.5

**Closed by BrainStone** 2017-06-24 19:49 UTC
Labels: Bug
