### ISSUE TITLE
update-check problem ("Could not fetch the latest version")

### ISSUE THREAD

**Issue by RedstoneFuture** [AuraDevelopmentTeam/BungeeChat2#98] opened 2020-01-13 02:01 UTC
#### Issue Description: 

With the bungeecord server-start currently the plugin get warnings because:

`§eCould not fetch the latest version!
java.io.FileNotFoundException: https://www.spigotmc.org/api/general.php`

The side is invalid. I think this is the reason.

full warning (from log): https://pastebin.com/7ruXZAYp

More over I deactivated the Update-Check but I get still the warnings.

```
    VersionChecker:
      enabled: false
      checkOnAdminLogin: true
```

#### Steps to reproduce:

1. restart the BC & check the console

____
#### Affected Versions: 

- Minecraft: 1.13.2
- BungeeChat:  2.1.6.855

**Comment by BrainStone** [comment] 2020-01-13 02:01
Duplicate of #97

**Closed by BrainStone** 2020-01-13 02:01 UTC

**Comment by RedstoneFuture** [comment] 2020-01-13 02:03
Ah, okay .. sry :)
