### ISSUE TITLE
[Bug]: Error dispatching event ChatEvent

### ISSUE THREAD

**Issue by RedstoneFuture** [AuraDevelopmentTeam/BungeeChat2#54] opened 2018-03-10 16:40 UTC
#### Issue Description: 

Sometimes a user lose the cooperation with the bungeechat and the chatstyle is like vanilla minecraft. I think this fail come from bungeechat and not from bungee. And I get a error in the bungeecord log.

I will update whis report with more informations if I get more.

#### Steps to reproduce:

1. Join to the server.
2. Disconnect your internet.
3. Wait 18 sec.
4. Connect your internet.
5. You lose the server connection. Rejoin and you see a error in the bungeecord log and if you write you do not get your prefix like your bungeechat configuration.

(6.) After a new normal rejoin the prefix is correct and you do net get more errors.

Test with "RedstoneFuture":
![2018-03-10_18 45 18](https://user-images.githubusercontent.com/4140635/37245084-47c67080-2493-11e8-9ae6-bbbe95498e9c.png)

____
#### Affected Versions: 

- Minecraft: 1.12.2
- BungeeChat:  2.1.6.855

#### Your most recent log or stack trace file where the issue was present: 

stack tree on bungeecord:

https://pastebin.com/gP9vZWQM

**Comment by RedstoneFuture** [comment] 2018-03-10 17:46
EDIT: see Steps to reproduce

**Comment by BrainStone** [comment] 2018-03-10 19:37
That looks like a tough one...

**Comment by RedstoneFuture** [comment] 2018-03-14 23:40
Another test:

1. join of the server
2. join with a second client of the server too
 => the first was kicked from the server and the second client has this bungeechat problem

**Comment by BrainStone** [comment] 2019-04-01 15:43
Has this been fixed with the latest dev version?

**Comment by BrainStone** [comment] 2020-03-30 01:17
Closing for now. Feel free to reopen if it's not fixed.

**Comment by RedstoneFuture** [comment] 2020-03-30 01:44
Oh, yea... Sorry.

**Comment by MrVoltz** [comment] 2020-10-27 17:36
Hi, I would like to reopen this issue. We are currently having this on our server. It starts when two simultaneous connections for the same player are attempted (for example when the first hasn't timeouted yet).

This error happened in only one occasion, it seems that there are some synchronization problems in your code:
```
[17:14:04] [Netty Worker IO Thread #3/WARN]: Error dispatching event BungeeChatJoinEvent(player=xxx) to listener 
dev.aura.bungeechat.account.BungeecordAccountManager@30e6a763
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:1.8.0_191]
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:1.8.0_191]
        at dev.aura.bungeechat.account.BungeecordAccountManager.loadAccount(BungeecordAccountManager.java:66) ~[?:?]
        at dev.aura.bungeechat.account.BungeecordAccountManager.onPlayerConnect(BungeecordAccountManager.java:112) ~[?
:?]
        at sun.reflect.GeneratedMethodAccessor31.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[BungeeCord.jar:git:Travertine
-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.16-R0.4-S
NAPSHOT:10048da:154]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453) ~[BungeeCord.jar:git:Travertine-
Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at dev.aura.bungeechat.listener.BungeeChatEventsListener.onPlayerServerSwitch(BungeeChatEventsListener.java:44
) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]
```

Then of course your HashMap gets corruped and chat totally stops working until the offending player leaves the game or is kicked. At the time of writing, this error has happened two times. 
```
[17:14:04] [Netty Worker IO Thread #3/WARN]: Error dispatching event BungeeChatJoinEvent(player=xxx) to listener dev.aura.bungeechat.listener.JoinMessageListener@6bbe50c9
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_191]
        at dev.aura.bungeechat.permission.PermissionManager.hasPermission(PermissionManager.java:43) ~[?:?]
        at dev.aura.bungeechat.message.MessagesService.lambda$getPermissionPredicate$12(MessagesService.java:415) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_191]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_191]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_191]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_191]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_191]
        at dev.aura.bungeechat.message.MessagesService.sendToMatchingPlayers(MessagesService.java:358) ~[?:?]
        at dev.aura.bungeechat.message.MessagesService.sendJoinMessage(MessagesService.java:236) ~[?:?]
        at dev.aura.bungeechat.message.MessagesService.sendJoinMessage(MessagesService.java:222) ~[?:?]
        at dev.aura.bungeechat.listener.JoinMessageListener.onPlayerJoin(JoinMessageListener.java:19) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at dev.aura.bungeechat.listener.BungeeChatEventsListener.onPlayerServerSwitch(BungeeChatEventsListener.java:44) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]
```

I think you should synchronize the HashMap and implement some sort of reference counting for the join and leave events. So when player joins 2 times and leaves 1 time, the HashMap entry doesn't get cleared. Or do you have any other suggestions?

**Comment by MrVoltz** [comment] 2020-10-27 20:48
I think the issue is in https://github.com/AuraDevelopmentTeam/BungeeChat2/blob/master/src/main/java/dev/aura/bungeechat/listener/BungeeChatEventsListener.java, because your code handles just two duplicate joins. If the player joins for the third time in a short timeframe, it bugs out. I'll rewrite that using a HashMap, test it and submit a PR.

**Comment by BrainStone** [comment] 2020-10-27 20:49
Sounds good to me

**Closed** 2020-12-22 00:30 UTC
Labels: Bug
